SHELL = /bin/bash

CXX = icpc

CXXFLAGS = -I/apps/vtk/5.0.2/include/vtk-5.0 -I/apps/parmetis/3.1/include -I../eigen-2.0 -I../metric_tensor/include -I../include -I../smooth/include -I../functionals/include -O2 -openmp -Wno-deprecated

LIBS = -L/apps/vtk/5.0.2/lib -L/apps/parmetis/3.1/lib -lguide -liomp5 -lpthread -L/usr/X11R6/lib64/ -lvtkIO -lvtkCommon -lvtkFiltering -lvtkIO -lmetis -lvtkexpat -lvtkpng -lvtkjpeg -lvtkMPEG2Encode -lvtktiff -lvtkzlib -lvtkDICOMParser

TEST_SRC = $(wildcard src/*.cpp)
TEST_BIN = $(patsubst src/%.cpp,bin/%,$(TEST_SRC))

.SUFFIXES: .cpp .o

.cpp.o:
	$(CXX) $(CXXFLAGS) -c $<

default: test

test: $(TEST_BIN)
      python ./unittest bin

bin/%: src/%.cpp
       $(CXX) $(CXXFLAGS) -o $@ $< $(LIBS)

clean:
	rm -rf *.o $(TEST_BIN)
