#!/usr/bin/env python

import os
import os.path
import glob
import stat

class UnitTest:
    def __init__(self, exe):
        self.exe = os.curdir + os.sep + exe.split(os.sep)[-1]
        self.verbose = True
        self.dir = os.sep.join((os.curdir + os.sep + exe).split(os.sep)[:-1])
        self.cwd = os.getcwd()

    def log(self, msg):
        if self.verbose and msg != '':
            print "    %s: %s" % (self.exe.split('/')[-1], msg)

    def run(self):
        os.chdir(self.dir)
#        self.log("chdir " + self.dir)
#        self.log("running")
        f = os.popen(self.exe)
        self.output = f.read()
        os.chdir(self.cwd)
        
        exitStatus = f.close()
        if exitStatus is None:
          return 0
        else:
          return exitStatus

    def parse(self):
        passcount = 0
        warncount = 0
        failcount = 0

        for line in self.output.split('\n'):
            line = line.lstrip()
            #self.log(line)
            if "pass" in line: passcount = passcount + 1
            if "fail" in line: failcount = failcount + 1

        return (passcount, warncount, failcount)

class UnitTestHarness:
    def __init__(self, dir):
        self.tests = []
        if dir[-1] == '/': dir = dir + "*"
        else: dir = dir + "/*"

        files = glob.glob(dir)
        for file in files:
            if not os.path.isdir(file) and stat.S_IXUSR & os.stat(file)[stat.ST_MODE]:
                self.tests.append(UnitTest(file))

    def run(self):
        passcount = 0
        warncount = 0
        failcount = 0

        warntests = []
        failtests = []

        for test in self.tests:
            exitStatus = test.run()
            
            (P, W, F) = test.parse()

            if (W, F) == (0, 0) and P > 0:
              if P == 1:
                test.log("1 pass")
              else:
                test.log("%d passes" % P)
            elif F > 0:
              if F == 1:
                test.log("1 fail")
              else:
                test.log("%d failures" % F)

            if (P, W, F) == (0, 0, 0):
              test.log("no output")
              warncount += 1
              warntests.append(test.exe)

            if W > 0:
              warntests.append(test.exe)

            if F > 0:
              failtests.append(test.exe)
              
            if not exitStatus == 0:
              print "    Failure: non-zero exit code from test"
              failcount += 1
              if not test.exe in failtests:
	        failtests.append(test.exe)

            passcount += P
            warncount += W
            failcount += F

        print "  RESULTS"
        print "    Passes:   %d" % passcount
        if len(failtests) == 0:
            print "    Failures: %d" % failcount
        else:
            print "    Failures: %d; tests = %s" % (failcount, failtests)

if __name__ == "__main__":
    import sys

    if "--electricfence" in sys.argv:
      os.putenv("LD_PRELOAD", "/usr/lib/libefence.so.0.0")
      os.putenv("EF_DISABLE_BANNER", "1")

    TestHarness = UnitTestHarness(sys.argv[-1])
    TestHarness.run()
