/* Start of code generated by generate_Steiner_ellipse_3d.py. Warning - be careful about modifying
   any of the generated code directly.  Any changes/fixes should be done
   in the code generation script generation.*/


#ifndef GENERATE_STEINER_ELLIPSE_3D_H
#define GENERATE_STEINER_ELLIPSE_3D_H

namespace pragmatic
{

void generate_Steiner_ellipse(const double *x1, const double *x2, const double *x3, const double *x4, double *sm);

}

#endif
