FIND_PATH(METIS_INCLUDE_DIR metis.h
  $ENV{METIS_DIR}/include
  /usr/local/include
  /usr/include
  /usr/include/metis
  )
message( STATUS ${METIS_INCLUDE_DIR} )

FIND_LIBRARY(METIS_LIBRARY metis
  $ENV{METIS_DIR}/lib
  /usr/local/lib
  /usr/lib
  )

IF(METIS_INCLUDE_DIR)
  ADD_DEFINITIONS(-DHAVE_METIS)
  IF(METIS_LIBRARY)
    SET( METIS_LIBRARIES ${METIS_LIBRARY})
    SET( METIS_FOUND "YES" )
  ENDIF(METIS_LIBRARY)
ENDIF(METIS_INCLUDE_DIR)

MARK_AS_ADVANCED( METIS_INCLUDE_DIR METIS_LIBRARY )
