FIND_PATH(EGADS_INCLUDE_DIR egads.h
  ${ESP_PATH}/EngSketchPad/include
  )
FIND_LIBRARY(EGADS_LIBRARY egads
  ${ESP_PATH}/EngSketchPad/lib
  )
FIND_PATH(OC_LIBRARY_PATH libTKTopAlgo.so
  ${ESP_PATH}/OpenCASCADE-6.8.0/lib
  )

IF(EGADS_INCLUDE_DIR)
  ADD_DEFINITIONS(-DHAVE_EGADS)
  IF(EGADS_LIBRARY)
    SET( EGADS_LIBRARIES ${EGADS_LIBRARY})
    IF(OC_LIBRARY_PATH)
      SET( EGADS_FOUND "YES" )
    ENDIF(OC_LIBRARY_PATH)
  ENDIF(EGADS_LIBRARY)
ENDIF(EGADS_INCLUDE_DIR)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(EGADS DEFAULT_MSG EGADS_INCLUDE_DIR )

MARK_AS_ADVANCED( EGADS_INCLUDE_DIR EGADS_LIBRARY OC_LIBRARY )